version: '3.8'
services:
  dev:
    build: .devcontainer/.
    image: vecser:py3.10.2
    container_name: vecser-dev

    stdin_open: true
    tty: true

    ports:
      - "7979:80"

    working_dir: /workspaces

    volumes:
      - ./app:/workspaces

    command: "sh init.sh"

